# setup ----
# load package
library(odbc)
library(dplyr)
library(dbplyr)

# connect to db
con <- DBI::dbConnect(
  odbc::odbc(),
  Driver = "SQL Server",
  Server = "SPAC2SVR",
  Port = 1433
)


# explore ----
arrests <- tbl(con, in_schema("AnnualPulls.dbo", "arrests"))

# ...explore arrests...
# ...explore arrests...
# ...explore arrests...
# ...explore arrests...
# ...explore arrests...

arrestcharges <- tbl(con, in_schema("AnnualPulls.dbo", "arrestcharges"))

# ...explore arrest charges...
# ...explore arrest charges...
# ...explore arrest charges...
# ...explore arrest charges...
# ...explore arrest charges...

courtdisps <- tbl(con, in_schema("AnnualPulls.dbo", "courtdisps"))

# ...explore court dispositions...
# ...explore court dispositions...
# ...explore court dispositions...
# ...explore court dispositions...
# ...explore court dispositions...

sentences <- tbl(con, in_schema("AnnualPulls.dbo", "sentences"))

# ...explore sentences...
# ...explore sentences...
# ...explore sentences...
# ...explore sentences...
# ...explore sentences...
