# setup ----
# load package
library(odbc)
library(dplyr)
library(dbplyr)
library(ggplot2)

# connect to db
con <- DBI::dbConnect(
  odbc::odbc(),
  Driver = "SQL Server",
  Server = "SPAC2SVR",
  Port = 1433
)


# visualize ----
arrests <- tbl(con, in_schema("AnnualPulls.dbo", "arrests"))

# ...tidy arrests...
# ...tidy arrests...
# ...tidy arrests...
# ...tidy arrests...
# ...tidy arrests...

# ...visualize arrests...
# ...visualize arrests...
# ...visualize arrests...
# ...visualize arrests...
# ...visualize arrests...

arrestcharges <- tbl(con, in_schema("AnnualPulls.dbo", "arrestcharges"))

# ...tidy arrest charges...
# ...tidy arrest charges...
# ...tidy arrest charges...
# ...tidy arrest charges...
# ...tidy arrest charges...

# ...visualize arrest charges...
# ...visualize arrest charges...
# ...visualize arrest charges...
# ...visualize arrest charges...
# ...visualize arrest charges...

courtdisps <- tbl(con, in_schema("AnnualPulls.dbo", "courtdisps"))

# ...tidy court dispositions...
# ...tidy court dispositions...
# ...tidy court dispositions...
# ...tidy court dispositions...
# ...tidy court dispositions...

# ...visualize tidy court dispositions...
# ...visualize tidy court dispositions...
# ...visualize tidy court dispositions...
# ...visualize tidy court dispositions...
# ...visualize tidy court dispositions...

sentences <- tbl(con, in_schema("AnnualPulls.dbo", "sentences"))

# ...tidy sentences...
# ...tidy sentences...
# ...tidy sentences...
# ...tidy sentences...
# ...tidy sentences...

# ...visualize tidy sentences...
# ...visualize tidy sentences...
# ...visualize tidy sentences...
# ...visualize tidy sentences...
# ...visualize tidy sentences...
