# setup ----
# load package
library(odbc)
library(dplyr)
library(dbplyr)

# connect to db
con <- DBI::dbConnect(
  odbc::odbc(),
  Driver = "SQL Server",
  Server = "SPAC2SVR",
  Port = 1433
)


# model ----
arrests <- tbl(con, in_schema("AnnualPulls.dbo", "arrests"))

# ...tidy arrests...
# ...tidy arrests...
# ...tidy arrests...
# ...tidy arrests...
# ...tidy arrests...

# ...fit models to tidy arrests...
# ...fit models to tidy arrests...
# ...fit models to tidy arrests...
# ...fit models to tidy arrests...
# ...fit models to tidy arrests...

arrestcharges <- tbl(con, in_schema("AnnualPulls.dbo", "arrestcharges"))

# ...tidy arrest charges...
# ...tidy arrest charges...
# ...tidy arrest charges...
# ...tidy arrest charges...
# ...tidy arrest charges...

# ...fit models to tidy arrest charges...
# ...fit models to tidy arrest charges...
# ...fit models to tidy arrest charges...
# ...fit models to tidy arrest charges...
# ...fit models to tidy arrest charges...

courtdisps <- tbl(con, in_schema("AnnualPulls.dbo", "courtdisps"))

# ...tidy court dispositions...
# ...tidy court dispositions...
# ...tidy court dispositions...
# ...tidy court dispositions...
# ...tidy court dispositions...

# ...fit models to tidy court dispositions...
# ...fit models to tidy court dispositions...
# ...fit models to tidy court dispositions...
# ...fit models to tidy court dispositions...
# ...fit models to tidy court dispositions...

sentences <- tbl(con, in_schema("AnnualPulls.dbo", "sentences"))

# ...tidy sentences...
# ...tidy sentences...
# ...tidy sentences...
# ...tidy sentences...
# ...tidy sentences...

# ...fit models to tidy sentences...
# ...fit models to tidy sentences...
# ...fit models to tidy sentences...
# ...fit models to tidy sentences...
# ...fit models to tidy sentences...
