library(dplyr)

tidy_arrests <- function(df) {
  # ...tidy arrests...
  # ...tidy arrests...
  # ...tidy arrests...
  # ...tidy arrests...
  # ...tidy arrests...
}

tidy_arrestcharges <- function(df) {
  # ...tidy arrest charges...
  # ...tidy arrest charges...
  # ...tidy arrest charges...
  # ...tidy arrest charges...
  # ...tidy arrest charges...
}

tidy_courtdisps <- function(df) {
  # ...tidy court dispositions...
  # ...tidy court dispositions...
  # ...tidy court dispositions...
  # ...tidy court dispositions...
  # ...tidy court dispositions...
}

tidy_sentences <- function(df) {
  # ...tidy sentences...
  # ...tidy sentences...
  # ...tidy sentences...
  # ...tidy sentences...
  # ...tidy sentences...
}

# exports
list(
  arrests = tidy_arrests,
  arrestcharges = tidy_arrestcharges,
  courtdisps = tidy_courtdisps,
  sentences = tidy_sentences
)
