# setup ----
# load package
library(dplyr)

# load module
source("https://tinyurl.com/r-module/import_module.R")
import_module(path = "modules/chri.R", force = TRUE)


# analysis ----

# ...explore arrests...
# ...explore arrests...
# ...explore arrests...
# ...explore arrests...
# ...explore arrests...

# ...explore arrest charges...
# ...explore arrest charges...
# ...explore arrest charges...
# ...explore arrest charges...
# ...explore arrest charges...

# ...explore court dispositions...
# ...explore court dispositions...
# ...explore court dispositions...
# ...explore court dispositions...
# ...explore court dispositions...

# ...explore sentences...
# ...explore sentences...
# ...explore sentences...
# ...explore sentences...
# ...explore sentences...
