# setup ----
# load package
library(ggplot2)

# load module
source("https://tinyurl.com/r-module/import_module.R")
import_module(path = "modules/chri.R", force = TRUE)
import_module(path = "modules/tidy.R", force = TRUE)


# visualize ----

# ...visualize tidy arrest...
# ...visualize tidy arrest...
# ...visualize tidy arrest...
# ...visualize tidy arrest...
# ...visualize tidy arrest...

# ...visualize tidy arrest charges...
# ...visualize tidy arrest charges...
# ...visualize tidy arrest charges...
# ...visualize tidy arrest charges...
# ...visualize tidy arrest charges...

# ...visualize tidy court dispositions...
# ...visualize tidy court dispositions...
# ...visualize tidy court dispositions...
# ...visualize tidy court dispositions...
# ...visualize tidy court dispositions...

# ...visualize tidy sentences...
# ...visualize tidy sentences...
# ...visualize tidy sentences...
# ...visualize tidy sentences...
# ...visualize tidy sentences...
