# setup ----
# load module
source("https://tinyurl.com/r-module/import_module.R")
import_module(path = "modules/chri.R", force = TRUE)
import_module(path = "modules/tidy.R", force = TRUE)


# model ----

# ...fit models to tidy arrest...
# ...fit models to tidy arrest...
# ...fit models to tidy arrest...
# ...fit models to tidy arrest...
# ...fit models to tidy arrest...

# ...fit models to tidy arrest charges...
# ...fit models to tidy arrest charges...
# ...fit models to tidy arrest charges...
# ...fit models to tidy arrest charges...
# ...fit models to tidy arrest charges...

# ...fit models tidy court dispositions...
# ...fit models tidy court dispositions...
# ...fit models tidy court dispositions...
# ...fit models tidy court dispositions...
# ...fit models tidy court dispositions...

# ...fit models tidy sentences...
# ...fit models tidy sentences...
# ...fit models tidy sentences...
# ...fit models tidy sentences...
# ...fit models tidy sentences...
