# setup ----
library(odbc)
library(dplyr)
library(dbplyr)

# connect to db
con <- DBI::dbConnect(
  odbc::odbc(),
  Driver = "SQL Server",
  Server = "SPAC2SVR",
  Port = 1433
)

# connect to tables
arrests <- tbl(con, in_schema("AnnualPulls.dbo", "arrests")),
arrestcharges <- tbl(con, in_schema("AnnualPulls.dbo", "arrestcharges")),
courtdisps <- tbl(con, in_schema("AnnualPulls.dbo", "courtdisps")),
sentences <- tbl(con, in_schema("AnnualPulls.dbo", "sentences"))


# analysis ----

# ...explore arrests...
# ...explore arrests...
# ...explore arrests...
# ...explore arrests...
# ...explore arrests...

# ...explore arrest charges...
# ...explore arrest charges...
# ...explore arrest charges...
# ...explore arrest charges...
# ...explore arrest charges...

# ...explore court dispositions...
# ...explore court dispositions...
# ...explore court dispositions...
# ...explore court dispositions...
# ...explore court dispositions...

# ...explore sentences...
# ...explore sentences...
# ...explore sentences...
# ...explore sentences...
# ...explore sentences...
