# setup ----
library(odbc)
library(dplyr)
library(dbplyr)
library(ggplot2)

# connect to db
con <- DBI::dbConnect(
  odbc::odbc(),
  Driver = "SQL Server",
  Server = "SPAC2SVR",
  Port = 1433
)

# connect to tables
arrests <- tbl(con, in_schema("AnnualPulls.dbo", "arrests")),
arrestcharges <- tbl(con, in_schema("AnnualPulls.dbo", "arrestcharges")),
courtdisps <- tbl(con, in_schema("AnnualPulls.dbo", "courtdisps")),
sentences <- tbl(con, in_schema("AnnualPulls.dbo", "sentences"))

# define functions to tidy tables
tidy_arrests <- function(df) {
  # ...tidy arrests...
  # ...tidy arrests...
  # ...tidy arrests...
  # ...tidy arrests...
  # ...tidy arrests...
}

tidy_arrestcharges <- function(df) {
  # ...tidy arrest charges...
  # ...tidy arrest charges...
  # ...tidy arrest charges...
  # ...tidy arrest charges...
  # ...tidy arrest charges...
}

tidy_courtdisps <- function(df) {
  # ...tidy court dispositions...
  # ...tidy court dispositions...
  # ...tidy court dispositions...
  # ...tidy court dispositions...
  # ...tidy court dispositions...
}

tidy_sentences <- function(df) {
  # ...tidy sentences...
  # ...tidy sentences...
  # ...tidy sentences...
  # ...tidy sentences...
  # ...tidy sentences...
}


# visualize ---

# ...visualize tidy arrest...
# ...visualize tidy arrest...
# ...visualize tidy arrest...
# ...visualize tidy arrest...
# ...visualize tidy arrest...

# ...visualize tidy arrest charges...
# ...visualize tidy arrest charges...
# ...visualize tidy arrest charges...
# ...visualize tidy arrest charges...
# ...visualize tidy arrest charges...

# ...visualize tidy court dispositions...
# ...visualize tidy court dispositions...
# ...visualize tidy court dispositions...
# ...visualize tidy court dispositions...
# ...visualize tidy court dispositions...

# ...visualize tidy sentences...
# ...visualize tidy sentences...
# ...visualize tidy sentences...
# ...visualize tidy sentences...
# ...visualize tidy sentences...
