# setup ----
library(odbc)
library(dplyr)
library(dbplyr)

# connect to db
con <- DBI::dbConnect(
  odbc::odbc(),
  Driver = "SQL Server",
  Server = "SPAC2SVR",
  Port = 1433
)

# connect to tables
arrests <- tbl(con, in_schema("AnnualPulls.dbo", "arrests")),
arrestcharges <- tbl(con, in_schema("AnnualPulls.dbo", "arrestcharges"))

# define functions to tidy tables
tidy_arrests <- function(df) {
  # ...tidy arrests...
  # ...tidy arrests...
  # ...tidy arrests...
  # ...tidy arrests...
  # ...tidy arrests...
}

tidy_arrestcharges <- function(df) {
  # ...tidy arrest charges...
  # ...tidy arrest charges...
  # ...tidy arrest charges...
  # ...tidy arrest charges...
  # ...tidy arrest charges...
}

tidy_courtdisps <- function(df) {
  # ...tidy court dispositions...
  # ...tidy court dispositions...
  # ...tidy court dispositions...
  # ...tidy court dispositions...
  # ...tidy court dispositions...
}

tidy_sentences <- function(df) {
  # ...tidy sentences...
  # ...tidy sentences...
  # ...tidy sentences...
  # ...tidy sentences...
  # ...tidy sentences...
}


# model ----

# ...fit models to tidy arrest...
# ...fit models to tidy arrest...
# ...fit models to tidy arrest...
# ...fit models to tidy arrest...
# ...fit models to tidy arrest...

# ...fit models to tidy arrest charges...
# ...fit models to tidy arrest charges...
# ...fit models to tidy arrest charges...
# ...fit models to tidy arrest charges...
# ...fit models to tidy arrest charges...

# ...fit models tidy court dispositions...
# ...fit models tidy court dispositions...
# ...fit models tidy court dispositions...
# ...fit models tidy court dispositions...
# ...fit models tidy court dispositions...

# ...fit models tidy sentences...
# ...fit models tidy sentences...
# ...fit models tidy sentences...
# ...fit models tidy sentences...
# ...fit models tidy sentences...
