# setup ----
# load package
library(odbc)
library(dplyr)
library(dbplyr)
library(ggplot2)

# connect to db
con <- DBI::dbConnect(
  odbc::odbc(),
  Driver = "SQL Server",
  Server = "SPAC2SVR",
  Port = 1433
)


# explore ----
arrests <- tbl(con, in_schema("AnnualPulls.dbo", "arrests"))

# ...explore arrests...
# ...explore arrests...
# ...explore arrests...
# ...explore arrests...
# ...explore arrests...

arrestcharges <- tbl(con, in_schema("AnnualPulls.dbo", "arrestcharges"))

# ...explore arrest charges...
# ...explore arrest charges...
# ...explore arrest charges...
# ...explore arrest charges...
# ...explore arrest charges...

courtdisps <- tbl(con, in_schema("AnnualPulls.dbo", "courtdisps"))

# ...explore court dispositions...
# ...explore court dispositions...
# ...explore court dispositions...
# ...explore court dispositions...
# ...explore court dispositions...

sentences <- tbl(con, in_schema("AnnualPulls.dbo", "sentences"))

# ...explore sentences...
# ...explore sentences...
# ...explore sentences...
# ...explore sentences...
# ...explore sentences...


# visualize ----

# ...tidy arrests...
# ...tidy arrests...
# ...tidy arrests...
# ...tidy arrests...
# ...tidy arrests...

# ...visualize tidy arrests...
# ...visualize tidy arrests...
# ...visualize tidy arrests...
# ...visualize tidy arrests...
# ...visualize tidy arrests...

# ...tidy arrest charges...
# ...tidy arrest charges...
# ...tidy arrest charges...
# ...tidy arrest charges...
# ...tidy arrest charges...

# ...visualize tidy arrest charges...
# ...visualize tidy arrest charges...
# ...visualize tidy arrest charges...
# ...visualize tidy arrest charges...
# ...visualize tidy arrest charges...

# ...tidy court dispositions...
# ...tidy court dispositions...
# ...tidy court dispositions...
# ...tidy court dispositions...
# ...tidy court dispositions...

# ...visualize tidy court dispositions...
# ...visualize tidy court dispositions...
# ...visualize tidy court dispositions...
# ...visualize tidy court dispositions...
# ...visualize tidy court dispositions...

# ...tidy sentences...
# ...tidy sentences...
# ...tidy sentences...
# ...tidy sentences...
# ...tidy sentences...

# ...visualize tidy sentences...
# ...visualize tidy sentences...
# ...visualize tidy sentences...
# ...visualize tidy sentences...
# ...visualize tidy sentences...


# model ----

# ...fit models to tidy arrest...
# ...fit models to tidy arrest...
# ...fit models to tidy arrest...
# ...fit models to tidy arrest...
# ...fit models to tidy arrest...

# ...fit models to tidy arrest charges
# ...fit models to tidy arrest charges
# ...fit models to tidy arrest charges
# ...fit models to tidy arrest charges
# ...fit models to tidy arrest charges

# ...fit models to tidy court dispositions...
# ...fit models to tidy court dispositions...
# ...fit models to tidy court dispositions...
# ...fit models to tidy court dispositions...
# ...fit models to tidy court dispositions...

# ...fit models to tidy sentences...
# ...fit models to tidy sentences...
# ...fit models to tidy sentences...
# ...fit models to tidy sentences...
# ...fit models to tidy sentences...
